package com.it5240.sportfriend.model.exception;

public enum ExceptionType {
    USER_NOT_FOUND,
    FRIEND_REQUEST_NOT_FOUND,
    COMMENT_NOT_FOUND,
    POST_NOT_FOUND,
    ROOM_NOT_FOUND,
    TOURNAMENT_NOT_FOUND,
    SPORT_NOT_FOUND,
    TOURNAMENT_POST_NOT_FOUND,
    SIGNUP_NOT_FOUND,
    UNAUTHORIZED,
    PARAMETER_NOT_ENOUGH,
    PHONE_NUMBER_EXISTED,
    FILE_IS_NOT_IMAGE,
    PASSWORD_NOT_MATCH,
}
